export const PASSENGER_DATA = {
  "passengers": [
    { "id": "P020", "name": "Etta Ramesh", "aliases": "" },
    { "id": "P021", "name": "Manjula", "aliases": "Shireesha" },
    { "id": "P022", "name": "Kavya", "aliases": "Kanya" },
    { "id": "P023", "name": "Suresh", "aliases": "" },
    { "id": "P024", "name": "Veena", "aliases": "" },
    { "id": "P025", "name": "Laxmi Kumar", "aliases": "" },
    { "id": "P026", "name": "Tippu", "aliases": "" },
    { "id": "P027", "name": "Kishan B", "aliases": "Kishan" },
    { "id": "P028", "name": "Vanaja B", "aliases": "Vanaja" },
    { "id": "P029", "name": "Srikumar", "aliases": "" },
    { "id": "P030", "name": "Srijan", "aliases": "" },
    { "id": "P031", "name": "Sragni", "aliases": "" },
    { "id": "P032", "name": "Prasad", "aliases": "" },
    { "id": "P033", "name": "Jaysri", "aliases": "Vijaya" },
    { "id": "P035", "name": "Premsai", "aliases": "Tharan,Tharun" },
    { "id": "P034", "name": "Latha", "aliases": "Akanksha" },
    { "id": "P036", "name": "Lachiah", "aliases": "" },
    { "id": "P037", "name": "Srimathi", "aliases": "" },
    { "id": "P038", "name": "Praveen", "aliases": "" },
    { "id": "P039", "name": "Ramu", "aliases": "Balaji" },
    { "id": "P040", "name": "Srivani", "aliases": "Sadanandam" },
    { "id": "P041", "name": "Arun", "aliases": "" },
    { "id": "P042", "name": "Ravi Teja", "aliases": "" },
    { "id": "P043", "name": "Naveen", "aliases": "" },
    { "id": "P044", "name": "Shoba Rani", "aliases": "" },
    { "id": "P045", "name": "Aparna", "aliases": "Sujatha" },
    { "id": "P046", "name": "Aparna Husband", "aliases": "Jaya Prakash" },
    { "id": "P047", "name": "Arram Nithish", "aliases": "" },
    { "id": "P048", "name": "Yashwanth Mya", "aliases": "" },
    { "id": "P049", "name": "Thota Ravi", "aliases": "" },
    { "id": "P050", "name": "Shireesha", "aliases": "Shireesha Thota" },
    { "id": "P051", "name": "Nanditha", "aliases": "" },
    { "id": "P052", "name": "Deva Devi", "aliases": "" },
    { "id": "P053", "name": "Sai Vineeth", "aliases": "" },
    { "id": "P054", "name": "Raja", "aliases": "" },
    { "id": "P055", "name": "Etta Swetha", "aliases": "" },
    { "id": "P056", "name": "Jyothi Sri", "aliases": "" },
    { "id": "P057", "name": "Soma Shivadhar", "aliases": "" },
    { "id": "P058", "name": "Soma Swetha", "aliases": "" },
    { "id": "P059", "name": "Ravi Lakendla", "aliases": "Rani Lakendla" },
    { "id": "P060", "name": "Padma Lakendla", "aliases": "" },
    { "id": "P063", "name": "Dr. Padma", "aliases": "" },
    { "id": "P064", "name": "Soma Jyothi", "aliases": "" },
    { "id": "P065", "name": "Neeraja", "aliases": "" },
    { "id": "P066", "name": "Uday Ketan", "aliases": "" },
    { "id": "P067", "name": "Riya", "aliases": "" },
    { "id": "P068", "name": "Sravani", "aliases": "" },
    { "id": "P061", "name": "Sujith", "aliases": "Rakesh" },
    { "id": "P062", "name": "Kavya Sujith", "aliases": "Vijaya k,Kavya" },
    { "id": "P001", "name": "Varun", "aliases": "" },
    { "id": "P002", "name": "Harshitha", "aliases": "" },
    { "id": "P003", "name": "Hymavathi", "aliases": "" },
    { "id": "P004", "name": "Arundathi", "aliases": "Aparna" },
    { "id": "P005", "name": "Raju", "aliases": "" },
    { "id": "P006", "name": "Geetha", "aliases": "" },
    { "id": "P007", "name": "Varshith", "aliases": "" },
    { "id": "P008", "name": "Aishu", "aliases": "" },
    { "id": "P009", "name": "Rathnama", "aliases": "" },
    { "id": "P010", "name": "Raju P", "aliases": "Puppy" },
    { "id": "P011", "name": "Ravi Raju", "aliases": "" },
    { "id": "P012", "name": "Rathnama S", "aliases": "Medansh" },
    { "id": "P013", "name": "Nikesh", "aliases": "" },
    { "id": "P014", "name": "Vijaya Laxmi", "aliases": "" },
    { "id": "P015", "name": "Uday", "aliases": "" },
    { "id": "P016", "name": "Rajitha", "aliases": "" },
    { "id": "P017", "name": "Srinu mama", "aliases": "Srinu" },
    { "id": "P018", "name": "Jyothi Tammana", "aliases": "" },
    { "id": "P019", "name": "Meenakshi", "aliases": "" }
  ],
  "journeys": [
    { "id": "J1", "type": "UP", "train": "20707", "date": "26/04/2026", "time": "06:20", "from": "Warangal", "to": "Vijayawada" },
    { "id": "J2", "type": "DOWN", "train": "20708", "date": "26/04/2026", "time": "18:20", "from": "Vijayawada", "to": "Warangal" }
  ],
  "assignments": [
    { "passenger_id": "P020", "journey_id": "J1", "coach": "C8", "seat": 14 },
    { "passenger_id": "P021", "journey_id": "J1", "coach": "C8", "seat": 15 },
    { "passenger_id": "P022", "journey_id": "J1", "coach": "C8", "seat": 16 },
    { "passenger_id": "P023", "journey_id": "J1", "coach": "C8", "seat": 17 },
    { "passenger_id": "P024", "journey_id": "J1", "coach": "C6", "seat": 10 },
    { "passenger_id": "P025", "journey_id": "J1", "coach": "C6", "seat": 11 },
    { "passenger_id": "P026", "journey_id": "J1", "coach": "C6", "seat": 12 },
    { "passenger_id": "P027", "journey_id": "J1", "coach": "C6", "seat": 13 },
    { "passenger_id": "P028", "journey_id": "J1", "coach": "C6", "seat": 14 },
    { "passenger_id": "P029", "journey_id": "J1", "coach": "C6", "seat": 15 },
    { "passenger_id": "P030", "journey_id": "J1", "coach": "C6", "seat": 2 },
    { "passenger_id": "P031", "journey_id": "J1", "coach": "C6", "seat": 3 },
    { "passenger_id": "P032", "journey_id": "J1", "coach": "C6", "seat": 4 },
    { "passenger_id": "P033", "journey_id": "J1", "coach": "C6", "seat": 5 },
    { "passenger_id": "P035", "journey_id": "J1", "coach": "C6", "seat": 6 },
    { "passenger_id": "P034", "journey_id": "J1", "coach": "C6", "seat": 7 },
    { "passenger_id": "P036", "journey_id": "J1", "coach": "C6", "seat": 20 },
    { "passenger_id": "P037", "journey_id": "J1", "coach": "C6", "seat": 21 },
    { "passenger_id": "P038", "journey_id": "J1", "coach": "C6", "seat": 22 },
    { "passenger_id": "P039", "journey_id": "J1", "coach": "C6", "seat": 23 },
    { "passenger_id": "P040", "journey_id": "J1", "coach": "C6", "seat": 24 },
    { "passenger_id": "P041", "journey_id": "J1", "coach": "C6", "seat": 25 },
    { "passenger_id": "P042", "journey_id": "J1", "coach": "C10", "seat": 20 },
    { "passenger_id": "P043", "journey_id": "J1", "coach": "C10", "seat": 21 },
    { "passenger_id": "P044", "journey_id": "J1", "coach": "C10", "seat": 22 },
    { "passenger_id": "P045", "journey_id": "J1", "coach": "C10", "seat": 23 },
    { "passenger_id": "P046", "journey_id": "J1", "coach": "C10", "seat": 24 },
    { "passenger_id": "P047", "journey_id": "J1", "coach": "C10", "seat": 25 },
    { "passenger_id": "P048", "journey_id": "J1", "coach": "C10", "seat": 10 },
    { "passenger_id": "P049", "journey_id": "J1", "coach": "C10", "seat": 11 },
    { "passenger_id": "P050", "journey_id": "J1", "coach": "C10", "seat": 12 },
    { "passenger_id": "P051", "journey_id": "J1", "coach": "C10", "seat": 13 },
    { "passenger_id": "P052", "journey_id": "J1", "coach": "C10", "seat": 4 },
    { "passenger_id": "P053", "journey_id": "J1", "coach": "C8", "seat": 35 },
    { "passenger_id": "P054", "journey_id": "J1", "coach": "C8", "seat": 34 },
    { "passenger_id": "P055", "journey_id": "J1", "coach": "C8", "seat": 33 },
    { "passenger_id": "P056", "journey_id": "J1", "coach": "C8", "seat": 32 },
    { "passenger_id": "P057", "journey_id": "J1", "coach": "C8", "seat": 31 },
    { "passenger_id": "P058", "journey_id": "J1", "coach": "C8", "seat": 30 },
    { "passenger_id": "P059", "journey_id": "J1", "coach": "C4", "seat": 16 },
    { "passenger_id": "P060", "journey_id": "J1", "coach": "C4", "seat": 15 },
    { "passenger_id": "P067", "journey_id": "J1", "coach": "C8", "seat": 12 },
    { "passenger_id": "P068", "journey_id": "J1", "coach": "C8", "seat": 13 },
    { "passenger_id": "P061", "journey_id": "J1", "coach": "C10", "seat": 14 },
    { "passenger_id": "P062", "journey_id": "J1", "coach": "C10", "seat": 15 },
    { "passenger_id": "P001", "journey_id": "J2", "coach": "C15", "seat": 20 },
    { "passenger_id": "P002", "journey_id": "J2", "coach": "C15", "seat": 21 },
    { "passenger_id": "P003", "journey_id": "J2", "coach": "C15", "seat": 22 },
    { "passenger_id": "P004", "journey_id": "J2", "coach": "C15", "seat": 28 },
    { "passenger_id": "P005", "journey_id": "J2", "coach": "C15", "seat": 25 },
    { "passenger_id": "P006", "journey_id": "J2", "coach": "C15", "seat": 10 },
    { "passenger_id": "P007", "journey_id": "J2", "coach": "C15", "seat": 12 },
    { "passenger_id": "P008", "journey_id": "J2", "coach": "C15", "seat": 13 },
    { "passenger_id": "P009", "journey_id": "J2", "coach": "C15", "seat": 23 },
    { "passenger_id": "P010", "journey_id": "J2", "coach": "C15", "seat": 14 },
    { "passenger_id": "P011", "journey_id": "J2", "coach": "C15", "seat": 24 },
    { "passenger_id": "P012", "journey_id": "J2", "coach": "C15", "seat": 11 },
    { "passenger_id": "P013", "journey_id": "J2", "coach": "C15", "seat": 27 },
    { "passenger_id": "P014", "journey_id": "J2", "coach": "C15", "seat": 15 },
    { "passenger_id": "P015", "journey_id": "J2", "coach": "C15", "seat": 26 },
    { "passenger_id": "P016", "journey_id": "J2", "coach": "C6", "seat": 78 },
    { "passenger_id": "P017", "journey_id": "J2", "coach": "C6", "seat": 77 },
    { "passenger_id": "P018", "journey_id": "J2", "coach": "C6", "seat": 71 },
    { "passenger_id": "P019", "journey_id": "J2", "coach": "C6", "seat": 70 },
    { "passenger_id": "P020", "journey_id": "J2", "coach": "C5", "seat": 43 },
    { "passenger_id": "P021", "journey_id": "J2", "coach": "C5", "seat": 44 },
    { "passenger_id": "P022", "journey_id": "J2", "coach": "C5", "seat": 45 },
    { "passenger_id": "P023", "journey_id": "J2", "coach": "C5", "seat": 46 },
    { "passenger_id": "P024", "journey_id": "J2", "coach": "C5", "seat": 50 },
    { "passenger_id": "P025", "journey_id": "J2", "coach": "C5", "seat": 51 },
    { "passenger_id": "P026", "journey_id": "J2", "coach": "C5", "seat": 52 },
    { "passenger_id": "P027", "journey_id": "J2", "coach": "C5", "seat": 53 },
    { "passenger_id": "P028", "journey_id": "J2", "coach": "C5", "seat": 54 },
    { "passenger_id": "P029", "journey_id": "J2", "coach": "C5", "seat": 55 },
    { "passenger_id": "P030", "journey_id": "J2", "coach": "C5", "seat": 10 },
    { "passenger_id": "P031", "journey_id": "J2", "coach": "C5", "seat": 11 },
    { "passenger_id": "P032", "journey_id": "J2", "coach": "C5", "seat": 12 },
    { "passenger_id": "P033", "journey_id": "J2", "coach": "C5", "seat": 13 },
    { "passenger_id": "P034", "journey_id": "J2", "coach": "C5", "seat": 15 },
    { "passenger_id": "P035", "journey_id": "J2", "coach": "C5", "seat": 14 },
    { "passenger_id": "P036", "journey_id": "J2", "coach": "C5", "seat": 20 },
    { "passenger_id": "P037", "journey_id": "J2", "coach": "C5", "seat": 21 },
    { "passenger_id": "P038", "journey_id": "J2", "coach": "C5", "seat": 22 },
    { "passenger_id": "P039", "journey_id": "J2", "coach": "C5", "seat": 23 },
    { "passenger_id": "P040", "journey_id": "J2", "coach": "C5", "seat": 24 },
    { "passenger_id": "P041", "journey_id": "J2", "coach": "C5", "seat": 25 },
    { "passenger_id": "P042", "journey_id": "J2", "coach": "C5", "seat": 60 },
    { "passenger_id": "P043", "journey_id": "J2", "coach": "C5", "seat": 61 },
    { "passenger_id": "P044", "journey_id": "J2", "coach": "C5", "seat": 62 },
    { "passenger_id": "P045", "journey_id": "J2", "coach": "C5", "seat": 63 },
    { "passenger_id": "P046", "journey_id": "J2", "coach": "C5", "seat": 64 },
    { "passenger_id": "P047", "journey_id": "J2", "coach": "C5", "seat": 66 },
    { "passenger_id": "P048", "journey_id": "J2", "coach": "C5", "seat": 1 },
    { "passenger_id": "P049", "journey_id": "J2", "coach": "C5", "seat": 2 },
    { "passenger_id": "P050", "journey_id": "J2", "coach": "C5", "seat": 3 },
    { "passenger_id": "P051", "journey_id": "J2", "coach": "C5", "seat": 4 },
    { "passenger_id": "P052", "journey_id": "J2", "coach": "C5", "seat": 70 },
    { "passenger_id": "P053", "journey_id": "J2", "coach": "C15", "seat": 47 },
    { "passenger_id": "P054", "journey_id": "J2", "coach": "C15", "seat": 46 },
    { "passenger_id": "P055", "journey_id": "J2", "coach": "C15", "seat": 45 },
    { "passenger_id": "P056", "journey_id": "J2", "coach": "C15", "seat": 44 },
    { "passenger_id": "P057", "journey_id": "J2", "coach": "C15", "seat": 43 },
    { "passenger_id": "P058", "journey_id": "J2", "coach": "C15", "seat": 42 },
    { "passenger_id": "P059", "journey_id": "J2", "coach": "C15", "seat": 48 },
    { "passenger_id": "P060", "journey_id": "J2", "coach": "C15", "seat": 49 },
    { "passenger_id": "P061", "journey_id": "J2", "coach": "C5", "seat": 5 },
    { "passenger_id": "P062", "journey_id": "J2", "coach": "C5", "seat": 6 },
    { "passenger_id": "P067", "journey_id": "J2", "coach": "C5", "seat": 41 },
    { "passenger_id": "P068", "journey_id": "J2", "coach": "C5", "seat": 42 }
  ]
};

export const WEDDING_DETAILS = {
  "bride": "Dr Sudheshna",
  "groom": "Dr Yashwanth",
  "wedding": {
    "date": "2026-04-26",
    "day": "Sunday",
    "time": "11:16 AM",
    "venue": {
      "name": "Samyukta Vedika",
      "address": "Yerneni Sri Ramachandra Rao Layout, Benz Circle, Vijayawada",
      "google_maps": "https://share.google/GivBwSHScCvVen8Ak"
    }
  },
  "reception": {
    "date": "2026-04-28",
    "time": "7:30 PM onwards",
    "venue": {
      "name": "Abhiram Gardens",
      "address": "Hunter Road, Warangal"
    }
  },
  "stay": {
    "name": "Guest Stay in Vijayawada",
    "google_maps": "https://share.google/GTEK2yTJpZGHW2isn"
  }
};

export const TRAIN_DETAILS = {
  "20707": {
    "train_number": "20707",
    "train_name": "Vande Bharat Express",
    "stops": [
      {"station": "Secunderabad Jn", "arrival": null, "departure": "05:00"},
      {"station": "Warangal", "arrival": "06:39", "departure": "06:40"},
      {"station": "Khammam", "arrival": "07:44", "departure": "07:45"},
      {"station": "Vijayawada Jn", "arrival": "09:00", "departure": "09:05"},
      {"station": "Eluru", "arrival": "09:49", "departure": "09:50"},
      {"station": "Rajahmundry", "arrival": "10:48", "departure": "10:50"},
      {"station": "Samalkot Jn", "arrival": "11:23", "departure": "11:25"},
      {"station": "Visakhapatnam", "arrival": "13:50", "departure": null}
    ],
    "coaches": ["T1", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11", "E1", "E2", "C12", "C13", "C14", "C15", "C16", "C17", "C18", "T1"]
  },
  "20708": {
    "train_number": "20708",
    "train_name": "Vande Bharat Express",
    "stops": [
      {"station": "Visakhapatnam (VSKP)", "arrival": null, "departure": "14:30"},
      {"station": "Samalkot Jn (SLO)", "arrival": "15:53", "departure": "15:55"},
      {"station": "Rajahmundry (RJY)", "arrival": "16:28", "departure": "16:30"},
      {"station": "Eluru (EE)", "arrival": "17:44", "departure": "17:45"},
      {"station": "Vijayawada Jn (BZA)", "arrival": "18:40", "departure": "18:45"},
      {"station": "Khammam (KMT)", "arrival": "20:04", "departure": "20:05"},
      {"station": "Warangal (WL)", "arrival": "21:14", "departure": "21:15"},
      {"station": "Secunderabad Jn (SC)", "arrival": "23:25", "departure": null}
    ],
    "coaches": [] // Same as 20707 but reversed maybe? User provided 20707 specifically.
  }
};
